openapi: 3.0.3
info:
  title: 'Betsjournal API'
  description: 'Manage and analyze your bets from anywhere with Betsjournal.'
  version: 1.0.0
servers:
  -
    url: 'https://betsjournal.io'
paths:
  /api/v1/bets:
    get:
      summary: 'Display all bets.'
      operationId: displayAllBets
      description: 'Get all of your recorded bets.'
      parameters:
        -
          in: query
          name: page
          description: 'Page to view.'
          example: 8
          required: false
          schema:
            type: integer
            description: 'Page to view.'
            example: 8
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 181
                      sport: eos
                      match: 'Odio blanditiis esse architecto ipsa ut labore aliquid.'
                      match_date: '1988-07-25'
                      match_time: '09:22'
                      bookie: voluptas
                      bet_type: necessitatibus
                      bet_description: 'Illum aut ea quis.'
                      bet_pick: ut
                      bet_size: 149.08
                      decimal_odd: 5.411
                      american_odd: 133.261
                      result: 2
                      cashout: 285.1
                      created_at: '2023-01-23T20:00:18.000000Z'
                      updated_at: '2023-01-23T20:00:18.000000Z'
                      categories: []
                    -
                      id: 182
                      sport: voluptatem
                      match: 'Rerum velit voluptate illum autem.'
                      match_date: '1974-10-13'
                      match_time: '18:21'
                      bookie: voluptas
                      bet_type: tempore
                      bet_description: 'Sit consectetur ut consequatur est.'
                      bet_pick: laborum
                      bet_size: 211.48
                      decimal_odd: 9.796
                      american_odd: -242.391
                      result: null
                      cashout: 108.07
                      created_at: '2023-01-23T20:00:18.000000Z'
                      updated_at: '2023-01-23T20:00:18.000000Z'
                      categories: []
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 181
                        sport: eos
                        match: 'Odio blanditiis esse architecto ipsa ut labore aliquid.'
                        match_date: '1988-07-25'
                        match_time: '09:22'
                        bookie: voluptas
                        bet_type: necessitatibus
                        bet_description: 'Illum aut ea quis.'
                        bet_pick: ut
                        bet_size: 149.08
                        decimal_odd: 5.411
                        american_odd: 133.261
                        result: 2
                        cashout: 285.1
                        created_at: '2023-01-23T20:00:18.000000Z'
                        updated_at: '2023-01-23T20:00:18.000000Z'
                        categories: []
                      -
                        id: 182
                        sport: voluptatem
                        match: 'Rerum velit voluptate illum autem.'
                        match_date: '1974-10-13'
                        match_time: '18:21'
                        bookie: voluptas
                        bet_type: tempore
                        bet_description: 'Sit consectetur ut consequatur est.'
                        bet_pick: laborum
                        bet_size: 211.48
                        decimal_odd: 9.796
                        american_odd: -242.391
                        result: null
                        cashout: 108.07
                        created_at: '2023-01-23T20:00:18.000000Z'
                        updated_at: '2023-01-23T20:00:18.000000Z'
                        categories: []
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 181
                        sport:
                          type: string
                          example: eos
                        match:
                          type: string
                          example: 'Odio blanditiis esse architecto ipsa ut labore aliquid.'
                        match_date:
                          type: string
                          example: '1988-07-25'
                        match_time:
                          type: string
                          example: '09:22'
                        bookie:
                          type: string
                          example: voluptas
                        bet_type:
                          type: string
                          example: necessitatibus
                        bet_description:
                          type: string
                          example: 'Illum aut ea quis.'
                        bet_pick:
                          type: string
                          example: ut
                        bet_size:
                          type: number
                          example: 149.08
                        decimal_odd:
                          type: number
                          example: 5.411
                        american_odd:
                          type: number
                          example: 133.261
                        result:
                          type: integer
                          example: 2
                        cashout:
                          type: number
                          example: 285.1
                        created_at:
                          type: string
                          example: '2023-01-23T20:00:18.000000Z'
                        updated_at:
                          type: string
                          example: '2023-01-23T20:00:18.000000Z'
                        categories:
                          type: array
                          example: []
      tags:
        - Bets
    post:
      summary: 'Store a newly created bet.'
      operationId: storeANewlyCreatedBet
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 183
                    sport: numquam
                    match: 'Sequi quam quo inventore asperiores voluptatibus enim.'
                    match_date: '1980-09-01'
                    match_time: '15:49'
                    bookie: voluptatem
                    bet_type: inventore
                    bet_description: 'Soluta aliquid qui recusandae laudantium sequi nobis.'
                    bet_pick: consectetur
                    bet_size: 113.56
                    decimal_odd: 5.995
                    american_odd: 177.946
                    result: 1
                    cashout: 196.69
                    created_at: '2023-01-23T20:00:18.000000Z'
                    updated_at: '2023-01-23T20:00:18.000000Z'
                    categories: []
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 183
                      sport:
                        type: string
                        example: numquam
                      match:
                        type: string
                        example: 'Sequi quam quo inventore asperiores voluptatibus enim.'
                      match_date:
                        type: string
                        example: '1980-09-01'
                      match_time:
                        type: string
                        example: '15:49'
                      bookie:
                        type: string
                        example: voluptatem
                      bet_type:
                        type: string
                        example: inventore
                      bet_description:
                        type: string
                        example: 'Soluta aliquid qui recusandae laudantium sequi nobis.'
                      bet_pick:
                        type: string
                        example: consectetur
                      bet_size:
                        type: number
                        example: 113.56
                      decimal_odd:
                        type: number
                        example: 5.995
                      american_odd:
                        type: number
                        example: 177.946
                      result:
                        type: integer
                        example: 1
                      cashout:
                        type: number
                        example: 196.69
                      created_at:
                        type: string
                        example: '2023-01-23T20:00:18.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-23T20:00:18.000000Z'
                      categories:
                        type: array
                        example: []
      tags:
        - Bets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                match:
                  type: string
                  description: 'The name of the match.'
                  example: 'Real Madrid vs Barcelona'
                bet_size:
                  type: number
                  description: 'The amount staked on the bet.'
                  example: 100.0
                odd:
                  type: float|int
                  description: 'The odd of the bet being offered.'
                  example: '2.5'
                sport:
                  type: string
                  description: 'The name of the sport.'
                  example: Soccer
                match_date:
                  type: string
                  description: 'The date of the match.'
                  example: '2023-1-25'
                match_time:
                  type: string
                  description: 'The time of the match.'
                  example: '21:00'
                bookie:
                  type: string
                  description: 'The name of bookie offering the bet.'
                  example: bet365
                bet_type:
                  type: string
                  description: 'The type of bet.'
                  example: 'Money Line'
                bet_description:
                  type: string
                  description: 'Brief description of the bet being placed.'
                  example: 'Champions League Final'
                bet_pick:
                  type: string
                  description: 'The name of the team being bet on.'
                  example: 'Real Madrid'
                result:
                  type: integer
                  description: 'The result of the bet being recorded, ranging from 0 to 2:'
                  example: 1
                cashout:
                  type: int|float
                  description: 'The amount for which the bet was cashed out.'
                  example: '50.0'
                categories:
                  type: array
                  description: ''
                  example: null
                  items:
                    type: string
                'categories[]':
                  type: integer
                  description: 'An array of categories for which the bet belogs to.'
                  example: 2
              required:
                - match
                - bet_size
                - odd
                - sport
                - match_date
                - match_time
                - bookie
                - bet_type
                - bet_pick
  '/api/v1/bets/{id}':
    get:
      summary: 'Show a single, specific bet.'
      operationId: showASingleSpecificBet
      description: 'See the details for a specific bet.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 184
                    sport: nisi
                    match: 'Voluptas debitis quia voluptas modi.'
                    match_date: '1976-05-18'
                    match_time: '09:47'
                    bookie: nihil
                    bet_type: est
                    bet_description: 'Magnam quae ut illo ut alias.'
                    bet_pick: explicabo
                    bet_size: 105.12
                    decimal_odd: 5.627
                    american_odd: 32.841
                    result: 2
                    cashout: 155.05
                    created_at: '2023-01-23T20:00:19.000000Z'
                    updated_at: '2023-01-23T20:00:19.000000Z'
                    categories: []
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 184
                      sport:
                        type: string
                        example: nisi
                      match:
                        type: string
                        example: 'Voluptas debitis quia voluptas modi.'
                      match_date:
                        type: string
                        example: '1976-05-18'
                      match_time:
                        type: string
                        example: '09:47'
                      bookie:
                        type: string
                        example: nihil
                      bet_type:
                        type: string
                        example: est
                      bet_description:
                        type: string
                        example: 'Magnam quae ut illo ut alias.'
                      bet_pick:
                        type: string
                        example: explicabo
                      bet_size:
                        type: number
                        example: 105.12
                      decimal_odd:
                        type: number
                        example: 5.627
                      american_odd:
                        type: number
                        example: 32.841
                      result:
                        type: integer
                        example: 2
                      cashout:
                        type: number
                        example: 155.05
                      created_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
                      categories:
                        type: array
                        example: []
      tags:
        - Bets
    put:
      summary: 'Update a bet.'
      operationId: updateABet
      description: 'Modify a previously recorded bet.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 185
                    sport: inventore
                    match: 'Voluptas tempora provident laborum quidem tempore aut iusto.'
                    match_date: '1992-03-30'
                    match_time: '19:01'
                    bookie: accusantium
                    bet_type: iure
                    bet_description: 'Laboriosam nihil laudantium deleniti temporibus.'
                    bet_pick: est
                    bet_size: 190.87
                    decimal_odd: 5.075
                    american_odd: 479.285
                    result: 0
                    cashout: 167.06
                    created_at: '2023-01-23T20:00:19.000000Z'
                    updated_at: '2023-01-23T20:00:19.000000Z'
                    categories: []
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 185
                      sport:
                        type: string
                        example: inventore
                      match:
                        type: string
                        example: 'Voluptas tempora provident laborum quidem tempore aut iusto.'
                      match_date:
                        type: string
                        example: '1992-03-30'
                      match_time:
                        type: string
                        example: '19:01'
                      bookie:
                        type: string
                        example: accusantium
                      bet_type:
                        type: string
                        example: iure
                      bet_description:
                        type: string
                        example: 'Laboriosam nihil laudantium deleniti temporibus.'
                      bet_pick:
                        type: string
                        example: est
                      bet_size:
                        type: number
                        example: 190.87
                      decimal_odd:
                        type: number
                        example: 5.075
                      american_odd:
                        type: number
                        example: 479.285
                      result:
                        type: integer
                        example: 0
                      cashout:
                        type: number
                        example: 167.06
                      created_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
                      categories:
                        type: array
                        example: []
      tags:
        - Bets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                match:
                  type: string
                  description: 'The name of the match.'
                  example: 'Real Madrid vs Barcelona'
                bet_size:
                  type: number
                  description: 'The amount staked on the bet.'
                  example: 100.0
                odd:
                  type: float|int
                  description: 'The odd of the bet being offered.'
                  example: '2.5'
                sport:
                  type: string
                  description: 'The name of the sport.'
                  example: Soccer
                match_date:
                  type: string
                  description: 'The date of the match.'
                  example: '2023-1-25'
                match_time:
                  type: string
                  description: 'The time of the match.'
                  example: '21:00'
                bookie:
                  type: string
                  description: 'The name of bookie offering the bet.'
                  example: bet365
                bet_type:
                  type: string
                  description: 'The type of bet.'
                  example: 'Money Line'
                bet_description:
                  type: string
                  description: 'Brief description of the bet being placed.'
                  example: 'Champions League Final'
                bet_pick:
                  type: string
                  description: 'The name of the team being bet on.'
                  example: 'Real Madrid'
                result:
                  type: integer
                  description: 'The result of the bet being recorded, ranging from 0 to 2:'
                  example: 1
                cashout:
                  type: int|float
                  description: 'The amount for which the bet was cashed out.'
                  example: '50.0'
                categories:
                  type: array
                  description: ''
                  example: null
                  items:
                    type: string
                'categories[]':
                  type: integer
                  description: 'An array of categories for which the bet belogs to.'
                  example: 2
              required:
                - match
                - bet_size
                - odd
                - sport
                - match_date
                - match_time
                - bookie
                - bet_type
                - bet_pick
    delete:
      summary: 'Delete bet.'
      operationId: deleteBet
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Bet deleted!'
                properties:
                  message:
                    type: string
                    example: 'Bet deleted!'
      tags:
        - Bets
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the bet.'
        example: 19
        required: true
        schema:
          type: integer
  /api/v1/categories/colors:
    get:
      summary: 'returns list of available category colors.'
      operationId: returnsListOfAvailableCategoryColors
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - blue
                  - indigo
                  - brown
                  - black
                  - yellow
      tags:
        - Categories
  /api/v1/categories:
    get:
      summary: 'Display all categories.'
      operationId: displayAllCategories
      description: 'Get all of your created categories.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 92
                      name: 'Inventore soluta.'
                      color: yellow
                      created_at: '2023-01-23T20:00:19.000000Z'
                      updated_at: '2023-01-23T20:00:19.000000Z'
                    -
                      id: 93
                      name: 'Sed est.'
                      color: yellow
                      created_at: '2023-01-23T20:00:19.000000Z'
                      updated_at: '2023-01-23T20:00:19.000000Z'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 92
                        name: 'Inventore soluta.'
                        color: yellow
                        created_at: '2023-01-23T20:00:19.000000Z'
                        updated_at: '2023-01-23T20:00:19.000000Z'
                      -
                        id: 93
                        name: 'Sed est.'
                        color: yellow
                        created_at: '2023-01-23T20:00:19.000000Z'
                        updated_at: '2023-01-23T20:00:19.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 92
                        name:
                          type: string
                          example: 'Inventore soluta.'
                        color:
                          type: string
                          example: yellow
                        created_at:
                          type: string
                          example: '2023-01-23T20:00:19.000000Z'
                        updated_at:
                          type: string
                          example: '2023-01-23T20:00:19.000000Z'
      tags:
        - Categories
    post:
      summary: 'Store a newly created category.'
      operationId: storeANewlyCreatedCategory
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 94
                    name: 'Iusto voluptas.'
                    color: black
                    created_at: '2023-01-23T20:00:19.000000Z'
                    updated_at: '2023-01-23T20:00:19.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 94
                      name:
                        type: string
                        example: 'Iusto voluptas.'
                      color:
                        type: string
                        example: black
                      created_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the category.'
                  example: 'Value Bets'
                color:
                  type: string
                  description: "The category's color."
                  example: indigo
              required:
                - name
                - color
  '/api/v1/categories/{id}':
    get:
      summary: 'Show a single, specific category.'
      operationId: showASingleSpecificCategory
      description: 'See the details for a specific category.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 95
                    name: 'Aperiam nam dolor.'
                    color: blue
                    created_at: '2023-01-23T20:00:19.000000Z'
                    updated_at: '2023-01-23T20:00:19.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 95
                      name:
                        type: string
                        example: 'Aperiam nam dolor.'
                      color:
                        type: string
                        example: blue
                      created_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
      tags:
        - Categories
    put:
      summary: 'Update a bet.'
      operationId: updateABet
      description: 'Modify a previously created category.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 96
                    name: 'Doloribus facilis quaerat.'
                    color: blue
                    created_at: '2023-01-23T20:00:19.000000Z'
                    updated_at: '2023-01-23T20:00:19.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 96
                      name:
                        type: string
                        example: 'Doloribus facilis quaerat.'
                      color:
                        type: string
                        example: blue
                      created_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-23T20:00:19.000000Z'
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the category.'
                  example: MMA
                color:
                  type: string
                  description: "The category's color."
                  example: blue
              required:
                - name
                - color
    delete:
      summary: 'Delete category.'
      operationId: deleteCategory
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Category deleted!'
                properties:
                  message:
                    type: string
                    example: 'Category deleted!'
      tags:
        - Categories
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 11
        required: true
        schema:
          type: integer
  /api/v1/bets/stats:
    get:
      summary: "Get the stats for all your bets.\n\nSee your bet's analysis, done for you so that you don't have to open excel."
      operationId: getTheStatsForAllYourBetsSeeYourBetsAnalysisDoneForYouSoThatYouDontHaveToOpenExcel
      description: ''
      parameters:
        -
          in: query
          name: categories
          description: 'Comma-separated list of categories to filter by.'
          example: '1,2'
          required: false
          schema:
            type: string
            description: 'Comma-separated list of categories to filter by.'
            example: '1,2'
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  totalBets: 76
                  totalWinBets: 39
                  totalLossBets: 17
                  totalNaBets: 5
                  totalCOBets: 15
                  averageOdds: 4.398
                  impliedProbability: '22.74'
                  actualProbability: '69.64'
                  totalGains: 8214.45
                  totalLosses: -43.630000000001
                  netProfit: 8258.08
                  biggestBet: '299.90'
                  biggestPayout: 1363.82036
                  biggestLoss: 286.28
                properties:
                  totalBets:
                    type: integer
                    example: 76
                  totalWinBets:
                    type: integer
                    example: 39
                  totalLossBets:
                    type: integer
                    example: 17
                  totalNaBets:
                    type: integer
                    example: 5
                  totalCOBets:
                    type: integer
                    example: 15
                  averageOdds:
                    type: number
                    example: 4.398
                  impliedProbability:
                    type: string
                    example: '22.74'
                  actualProbability:
                    type: string
                    example: '69.64'
                  totalGains:
                    type: number
                    example: 8214.45
                  totalLosses:
                    type: number
                    example: -43.630000000001
                  netProfit:
                    type: number
                    example: 8258.08
                  biggestBet:
                    type: string
                    example: '299.90'
                  biggestPayout:
                    type: number
                    example: 1363.82036
                  biggestLoss:
                    type: number
                    example: 286.28
      tags:
        - Stats
  /api/v1/user:
    get:
      summary: 'Get your account information.'
      operationId: getYourAccountInformation
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: 'Pedro Motta'
                  email: phpaivamotta@gmail.com
                  email_verified_at: null
                  odd_type: decimal
                  created_at: '2022-12-30T01:07:15.000000Z'
                  updated_at: '2023-01-09T03:38:15.000000Z'
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 'Pedro Motta'
                  email:
                    type: string
                    example: phpaivamotta@gmail.com
                  email_verified_at:
                    type: string
                    example: null
                  odd_type:
                    type: string
                    example: decimal
                  created_at:
                    type: string
                    example: '2022-12-30T01:07:15.000000Z'
                  updated_at:
                    type: string
                    example: '2023-01-09T03:38:15.000000Z'
      tags:
        - User
  /api/v1/value-bets/sports:
    get:
      summary: 'Sports list'
      operationId: sportsList
      description: 'Get list of available sports for which there are value bets.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - americanfootball_nfl
                  - americanfootball_nfl_super_bowl_winner
                  - aussierules_afl
                  - baseball_mlb_world_series_winner
                  - basketball_euroleague
                  - basketball_nba
                  - basketball_nba_championship_winner
                  - basketball_ncaab
                  - cricket_big_bash
                  - cricket_odi
                  - golf_masters_tournament_winner
                  - golf_pga_championship_winner
                  - golf_the_open_championship_winner
                  - golf_us_open_winner
                  - icehockey_nhl
                  - icehockey_nhl_championship_winner
                  - icehockey_sweden_allsvenskan
                  - icehockey_sweden_hockey_league
                  - mma_mixed_martial_arts
                  - rugbyleague_nrl
                  - soccer_argentina_primera_division
                  - soccer_australia_aleague
                  - soccer_belgium_first_div
                  - soccer_chile_campeonato
                  - soccer_denmark_superliga
                  - soccer_efl_champ
                  - soccer_england_efl_cup
                  - soccer_england_league1
                  - soccer_england_league2
                  - soccer_epl
                  - soccer_fa_cup
                  - soccer_france_ligue_one
                  - soccer_france_ligue_two
                  - soccer_germany_bundesliga
                  - soccer_germany_bundesliga2
                  - soccer_italy_serie_a
                  - soccer_italy_serie_b
                  - soccer_league_of_ireland
                  - soccer_mexico_ligamx
                  - soccer_netherlands_eredivisie
                  - soccer_norway_eliteserien
                  - soccer_poland_ekstraklasa
                  - soccer_portugal_primeira_liga
                  - soccer_spain_la_liga
                  - soccer_spain_segunda_division
                  - soccer_spl
                  - soccer_sweden_allsvenskan
                  - soccer_sweden_superettan
                  - soccer_switzerland_superleague
                  - soccer_turkey_super_league
                  - soccer_uefa_champs_league
                  - soccer_uefa_europa_conference_league
                  - soccer_uefa_europa_league
                  - tennis_atp_aus_open_singles
                  - tennis_wta_aus_open_singles
      tags:
        - 'Value Bets'
  /api/v1/value-bets:
    get:
      summary: 'Get value bets.'
      operationId: getValueBets
      description: 'Get a list of value bets for your selected bookie region and min. over value.'
      parameters:
        -
          in: query
          name: sport
          description: 'The selected sport market from list of available sports which can be obtained from the /value-bets/sports endpoint.'
          example: soccer_italy_serie_a
          required: true
          schema:
            type: string
            description: 'The selected sport market from list of available sports which can be obtained from the /value-bets/sports endpoint.'
            example: soccer_italy_serie_a
        -
          in: query
          name: regions
          description: 'Comma-separated list of bookie regions to filter by.'
          example: 'us,uk'
          required: true
          schema:
            type: string
            description: 'Comma-separated list of bookie regions to filter by.'
            example: 'us,uk'
        -
          in: query
          name: overValue
          description: 'Min. over value percentage to filter value bets by.'
          example: 20.0
          required: true
          schema:
            type: number
            description: 'Min. over value percentage to filter value bets by.'
            example: 20.0
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    home_team: 'Hellas Verona FC'
                    away_team: Lecce
                    sport: 'Serie A - Italy'
                    num_bookies_analyzed:
                      home_team: 32
                      away_team: 32
                      draw: 32
                    commence_time: '2023-01-21T14:00:00Z'
                    value_bets:
                      home_team:
                        Matchbook:
                          over_value: 0.0576
                          money_line: 2.52
                      away_team:
                        Bovada:
                          over_value: 0.07
                          money_line: 3.5
                        Betfair:
                          over_value: 0.0547
                          money_line: 3.45
                        Matchbook:
                          over_value: 0.0547
                          money_line: 3.45
                  -
                    home_team: Salernitana
                    away_team: Napoli
                    sport: 'Serie A - Italy'
                    num_bookies_analyzed:
                      home_team: 33
                      away_team: 33
                      draw: 33
                    commence_time: '2023-01-21T17:00:00Z'
                    value_bets:
                      home_team:
                        Ladbrokes:
                          over_value: 0.066
                          money_line: 10.5
                        Coral:
                          over_value: 0.1168
                          money_line: 11
                        'Bet Victor':
                          over_value: 0.1168
                          money_line: 11
                        'Sky Bet':
                          over_value: 0.1168
                          money_line: 11
                        Betfair:
                          over_value: 0.1168
                          money_line: 11
                        'William Hill (US)':
                          over_value: 0.066
                          money_line: 10.5
                        Matchbook:
                          over_value: 0.1168
                          money_line: 11
                      draw:
                        Betfair:
                          over_value: 0.0901
                          money_line: 6.4
                        SugarHouse:
                          over_value: 0.0645
                          money_line: 6.25
                        Matchbook:
                          over_value: 0.0901
                          money_line: 6.4
                        LowVig.ag:
                          over_value: 0.0815
                          money_line: 6.35
                        BetOnline.ag:
                          over_value: 0.0815
                          money_line: 6.35
      tags:
        - 'Value Bets'
tags:
  -
    name: Bets
    description: "\nManage your bet resources."
  -
    name: Categories
    description: "\nManage your category resources."
  -
    name: Stats
    description: ''
  -
    name: User
    description: ''
  -
    name: 'Value Bets'
    description: "\nGet value bet opportunities."
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
